export const titleDataProtect = [
  "DATA PROTECTION AT A GLANCE",
  "DATA COLLECTION ON OUR WEBSITE",
  "SOCIAL MEDIA",
  "ANALYTICS AND ADVERTISING GOOGLE ANALYTICS",
  "NEWSLETTER",
  "PLUGINS AND TOOLS",
  "RIGHTS",
  "WHICH LAW DO WE APPLY? AND WHERE IS THE LAW APPLIED?",
  "CAN THIS DECLARATION BE AMENDED?",
  "QUESTIONS ABOUT DATA PROTECTION? PLEASE, CONTACT US!",
];
